/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verificar liveness do processo */
        get: operations["HealthController_live"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verificar readiness e conexão PostgreSQL */
        get: operations["HealthController_ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar empresas e lojas autorizadas */
        get: operations["IdentityController_context"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/products/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consultar produto por código de barras */
        get: operations["CatalogController_lookup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar categorias da empresa */
        get: operations["CatalogController_categories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar localizações da loja */
        get: operations["LocationsController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/questionnaires/product-intake/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obter questionário de entrada vigente */
        get: operations["QuestionnairesController_current"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/questionnaires/product-intake/versions/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obter versão suportada do questionário */
        get: operations["QuestionnairesController_version"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/intake-submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Registrar coleta idempotente de produto e lote */
        post: operations["IntakeController_submit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sync/submissions/{clientRequestId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consultar resultado de uma sincronização */
        get: operations["SyncController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar lotes em ordem FEFO */
        get: operations["BatchesController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_live: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HealthController_ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    IdentityController_context: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Empresas, papéis e lojas autorizadas. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        user: {
                            /** Format: uuid */
                            id: string;
                            displayName: string;
                        };
                        companies: {
                            /** Format: uuid */
                            id: string;
                            name: string;
                            /** @enum {string} */
                            role: "COMPANY_ADMIN" | "STORE_MANAGER" | "STOCK_OPERATOR" | "VIEWER";
                            stores: {
                                /** Format: uuid */
                                id: string;
                                name: string;
                                timezone: string;
                            }[];
                        }[];
                    };
                };
            };
            /** @description Token ausente ou inválido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            /** @example LOCATION_NOT_FOUND */
                            code: string;
                            message: string;
                            retryable: boolean;
                            /** Format: uuid */
                            correlationId: string;
                            fields?: {
                                path?: string;
                                code?: string;
                            }[];
                        };
                    };
                };
            };
        };
    };
    CatalogController_lookup: {
        parameters: {
            query: {
                format: "EAN_8" | "EAN_13" | "UPC_A" | "UPC_E" | "INTERNAL";
                barcode: string;
            };
            header: {
                "X-Store-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Produto e barcode normalizado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        product: {
                            /** Format: uuid */
                            id: string;
                            name: string;
                            brand?: string | null;
                            /** Format: uuid */
                            categoryId: string;
                            /** @enum {string} */
                            unitOfMeasure: "UNIT" | "KG" | "G" | "L" | "ML";
                            packageContent?: {
                                value: string;
                                unit: string;
                            } | null;
                            salePrice: {
                                amount: string;
                                currency: string;
                            };
                            automaticPromotionEligible: boolean;
                            version: number;
                        };
                        barcode: {
                            rawValue: string;
                            format: string;
                            canonicalValue: string;
                        };
                    };
                };
            };
            /** @description Token ausente ou inválido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            /** @example LOCATION_NOT_FOUND */
                            code: string;
                            message: string;
                            retryable: boolean;
                            /** Format: uuid */
                            correlationId: string;
                            fields?: {
                                path?: string;
                                code?: string;
                            }[];
                        };
                    };
                };
            };
            /** @description Sem permissão para a operação. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            /** @example LOCATION_NOT_FOUND */
                            code: string;
                            message: string;
                            retryable: boolean;
                            /** Format: uuid */
                            correlationId: string;
                            fields?: {
                                path?: string;
                                code?: string;
                            }[];
                        };
                    };
                };
            };
            /** @description Produto não encontrado. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            /** @example LOCATION_NOT_FOUND */
                            code: string;
                            message: string;
                            retryable: boolean;
                            /** Format: uuid */
                            correlationId: string;
                            fields?: {
                                path?: string;
                                code?: string;
                            }[];
                        };
                    };
                };
            };
            /** @description Barcode inválido. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            /** @example LOCATION_NOT_FOUND */
                            code: string;
                            message: string;
                            retryable: boolean;
                            /** Format: uuid */
                            correlationId: string;
                            fields?: {
                                path?: string;
                                code?: string;
                            }[];
                        };
                    };
                };
            };
        };
    };
    CatalogController_categories: {
        parameters: {
            query?: {
                active?: boolean;
            };
            header: {
                "X-Store-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Categorias da empresa ativa. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: {
                            /** Format: uuid */
                            id: string;
                            name: string;
                            active: boolean;
                        }[];
                    };
                };
            };
            /** @description Token ausente ou inválido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            /** @example LOCATION_NOT_FOUND */
                            code: string;
                            message: string;
                            retryable: boolean;
                            /** Format: uuid */
                            correlationId: string;
                            fields?: {
                                path?: string;
                                code?: string;
                            }[];
                        };
                    };
                };
            };
            /** @description Sem permissão para a operação. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            /** @example LOCATION_NOT_FOUND */
                            code: string;
                            message: string;
                            retryable: boolean;
                            /** Format: uuid */
                            correlationId: string;
                            fields?: {
                                path?: string;
                                code?: string;
                            }[];
                        };
                    };
                };
            };
        };
    };
    LocationsController_list: {
        parameters: {
            query?: {
                active?: boolean;
            };
            header: {
                "X-Store-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Localizações da loja ativa. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: {
                            /** Format: uuid */
                            id: string;
                            code: string;
                            name: string;
                            active: boolean;
                        }[];
                    };
                };
            };
            /** @description Token ausente ou inválido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            /** @example LOCATION_NOT_FOUND */
                            code: string;
                            message: string;
                            retryable: boolean;
                            /** Format: uuid */
                            correlationId: string;
                            fields?: {
                                path?: string;
                                code?: string;
                            }[];
                        };
                    };
                };
            };
            /** @description Sem permissão para a operação. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            /** @example LOCATION_NOT_FOUND */
                            code: string;
                            message: string;
                            retryable: boolean;
                            /** Format: uuid */
                            correlationId: string;
                            fields?: {
                                path?: string;
                                code?: string;
                            }[];
                        };
                    };
                };
            };
        };
    };
    QuestionnairesController_current: {
        parameters: {
            query?: never;
            header: {
                "X-Store-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Questionário vigente, checksum e versão. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        version: number;
                        schemaVersion: number;
                        definition: unknown;
                        checksum: string;
                        /** Format: date-time */
                        publishedAt?: string;
                        /** Format: date-time */
                        supportedUntil?: string | null;
                    };
                };
            };
            /** @description ETag ainda vigente. */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token ausente ou inválido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            /** @example LOCATION_NOT_FOUND */
                            code: string;
                            message: string;
                            retryable: boolean;
                            /** Format: uuid */
                            correlationId: string;
                            fields?: {
                                path?: string;
                                code?: string;
                            }[];
                        };
                    };
                };
            };
            /** @description Sem permissão para a operação. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            /** @example LOCATION_NOT_FOUND */
                            code: string;
                            message: string;
                            retryable: boolean;
                            /** Format: uuid */
                            correlationId: string;
                            fields?: {
                                path?: string;
                                code?: string;
                            }[];
                        };
                    };
                };
            };
        };
    };
    QuestionnairesController_version: {
        parameters: {
            query?: never;
            header: {
                "X-Store-Id": string;
            };
            path: {
                /** @description Inteiro positivo. */
                version: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Versão publicada e ainda suportada. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        version: number;
                        schemaVersion: number;
                        definition: unknown;
                        checksum: string;
                        /** Format: date-time */
                        publishedAt?: string;
                        /** Format: date-time */
                        supportedUntil?: string | null;
                    };
                };
            };
            /** @description Token ausente ou inválido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            /** @example LOCATION_NOT_FOUND */
                            code: string;
                            message: string;
                            retryable: boolean;
                            /** Format: uuid */
                            correlationId: string;
                            fields?: {
                                path?: string;
                                code?: string;
                            }[];
                        };
                    };
                };
            };
            /** @description Sem permissão para a operação. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            /** @example LOCATION_NOT_FOUND */
                            code: string;
                            message: string;
                            retryable: boolean;
                            /** Format: uuid */
                            correlationId: string;
                            fields?: {
                                path?: string;
                                code?: string;
                            }[];
                        };
                    };
                };
            };
            /** @description Versão inexistente ou não suportada. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    IntakeController_submit: {
        parameters: {
            query?: never;
            header: {
                /** @description UUID do dispositivo usado também no rate limit. */
                "X-Device-Id"?: string;
                "X-Store-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: uuid
                     * @description UUID v4 imutável entre retries.
                     */
                    clientRequestId: string;
                    questionnaireVersion: number;
                    device: {
                        /** Format: uuid */
                        deviceId: string;
                        appVersion: string;
                        /** Format: date-time */
                        capturedAt: string;
                    };
                    barcode: {
                        value: string;
                        /** @enum {string} */
                        format: "EAN_8" | "EAN_13" | "UPC_A" | "UPC_E" | "INTERNAL";
                        /** @enum {string} */
                        source: "CAMERA" | "MANUAL" | "HARDWARE_READER";
                        /** @enum {boolean} */
                        confirmed: true;
                    };
                    product: {
                        /** @enum {string} */
                        mode: "EXISTING";
                        /** Format: uuid */
                        id: string;
                        observedVersion: number;
                    } | {
                        /** @enum {string} */
                        mode: "CREATE";
                        name: string;
                        brand?: string | null;
                        /** Format: uuid */
                        categoryId: string;
                        /** @enum {string} */
                        unitOfMeasure: "UNIT" | "KG" | "G" | "L" | "ML";
                        packageContent?: {
                            value: string;
                            unit: string;
                        } | null;
                        salePrice: {
                            amount: string;
                            /** @enum {string} */
                            currency: "BRL";
                        };
                        /** @default false */
                        automaticPromotionEligible?: boolean;
                    };
                    batch: {
                        /** Format: date */
                        expiryDate: string;
                        /** Format: date */
                        entryDate?: string;
                        batchNumber?: string | null;
                        quantity: string;
                        /** Format: uuid */
                        locationId: string;
                        unitCost?: {
                            amount: string;
                            /** @enum {string} */
                            currency: "BRL";
                        } | null;
                        observation?: string | null;
                        expiryBeforeEntryConfirmation?: {
                            /** @enum {boolean} */
                            confirmed: true;
                            reason: string;
                        };
                    };
                };
            };
        };
        responses: {
            /** @description Replay idempotente. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        submissionId: string;
                        /** Format: uuid */
                        clientRequestId: string;
                        /** @enum {string} */
                        status: "COMPLETED";
                        product: {
                            /** Format: uuid */
                            id: string;
                            created: boolean;
                            version: number;
                        };
                        batch: {
                            /** Format: uuid */
                            id: string;
                            /** Format: date */
                            expiryDate: string;
                            quantity: string;
                            /** Format: uuid */
                            locationId: string;
                        };
                        /** Format: uuid */
                        initialMovementId: string;
                        /** Format: date-time */
                        completedAt: string;
                    };
                };
            };
            /** @description Coleta criada atomicamente. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        submissionId: string;
                        /** Format: uuid */
                        clientRequestId: string;
                        /** @enum {string} */
                        status: "COMPLETED";
                        product: {
                            /** Format: uuid */
                            id: string;
                            created: boolean;
                            version: number;
                        };
                        batch: {
                            /** Format: uuid */
                            id: string;
                            /** Format: date */
                            expiryDate: string;
                            quantity: string;
                            /** Format: uuid */
                            locationId: string;
                        };
                        /** Format: uuid */
                        initialMovementId: string;
                        /** Format: date-time */
                        completedAt: string;
                    };
                };
            };
            /** @description Token ausente ou inválido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            /** @example LOCATION_NOT_FOUND */
                            code: string;
                            message: string;
                            retryable: boolean;
                            /** Format: uuid */
                            correlationId: string;
                            fields?: {
                                path?: string;
                                code?: string;
                            }[];
                        };
                    };
                };
            };
            /** @description Sem permissão para a operação. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            /** @example LOCATION_NOT_FOUND */
                            code: string;
                            message: string;
                            retryable: boolean;
                            /** Format: uuid */
                            correlationId: string;
                            fields?: {
                                path?: string;
                                code?: string;
                            }[];
                        };
                    };
                };
            };
            /** @description Conflito de idempotência, catálogo ou questionário. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            /** @example LOCATION_NOT_FOUND */
                            code: string;
                            message: string;
                            retryable: boolean;
                            /** Format: uuid */
                            correlationId: string;
                            fields?: {
                                path?: string;
                                code?: string;
                            }[];
                        };
                    };
                };
            };
            /** @description Payload ou regra inválida. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            /** @example LOCATION_NOT_FOUND */
                            code: string;
                            message: string;
                            retryable: boolean;
                            /** Format: uuid */
                            correlationId: string;
                            fields?: {
                                path?: string;
                                code?: string;
                            }[];
                        };
                    };
                };
            };
            /** @description Rate limit excedido. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            /** @example LOCATION_NOT_FOUND */
                            code: string;
                            message: string;
                            retryable: boolean;
                            /** Format: uuid */
                            correlationId: string;
                            fields?: {
                                path?: string;
                                code?: string;
                            }[];
                        };
                    };
                };
            };
        };
    };
    SyncController_get: {
        parameters: {
            query?: never;
            header: {
                "X-Store-Id": string;
            };
            path: {
                clientRequestId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resultado concluído da sincronização. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        submissionId: string;
                        /** Format: uuid */
                        clientRequestId: string;
                        /** @enum {string} */
                        status: "COMPLETED";
                        product: {
                            /** Format: uuid */
                            id: string;
                            created: boolean;
                            version: number;
                        };
                        batch: {
                            /** Format: uuid */
                            id: string;
                            /** Format: date */
                            expiryDate: string;
                            quantity: string;
                            /** Format: uuid */
                            locationId: string;
                        };
                        /** Format: uuid */
                        initialMovementId: string;
                        /** Format: date-time */
                        completedAt: string;
                    };
                };
            };
            /** @description Token ausente ou inválido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            /** @example LOCATION_NOT_FOUND */
                            code: string;
                            message: string;
                            retryable: boolean;
                            /** Format: uuid */
                            correlationId: string;
                            fields?: {
                                path?: string;
                                code?: string;
                            }[];
                        };
                    };
                };
            };
            /** @description Sem permissão para a operação. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            /** @example LOCATION_NOT_FOUND */
                            code: string;
                            message: string;
                            retryable: boolean;
                            /** Format: uuid */
                            correlationId: string;
                            fields?: {
                                path?: string;
                                code?: string;
                            }[];
                        };
                    };
                };
            };
            /** @description Submissão não encontrada no escopo. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            /** @example LOCATION_NOT_FOUND */
                            code: string;
                            message: string;
                            retryable: boolean;
                            /** Format: uuid */
                            correlationId: string;
                            fields?: {
                                path?: string;
                                code?: string;
                            }[];
                        };
                    };
                };
            };
        };
    };
    BatchesController_list: {
        parameters: {
            query?: {
                status?: "ACTIVE" | "DEPLETED" | "EXPIRED" | "DISCARDED";
                locationId?: string;
                expiryTo?: string;
                expiryFrom?: string;
                productId?: string;
                limit?: number;
                cursor?: string;
            };
            header: {
                "X-Store-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página FEFO de lotes da loja. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: {
                            /** Format: uuid */
                            id: string;
                            product: {
                                /** Format: uuid */
                                id: string;
                                name: string;
                                barcode: string | null;
                            };
                            batchNumber: string | null;
                            /** Format: date */
                            expiryDate: string;
                            daysRemaining: number;
                            quantity: string;
                            location: {
                                /** Format: uuid */
                                id: string;
                                code: string;
                                name: string;
                            };
                            /** @enum {string} */
                            status: "ACTIVE" | "DEPLETED" | "EXPIRED" | "DISCARDED";
                            /** Format: date-time */
                            createdAt: string;
                        }[];
                        nextCursor: string | null;
                    };
                };
            };
            /** @description Token ausente ou inválido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            /** @example LOCATION_NOT_FOUND */
                            code: string;
                            message: string;
                            retryable: boolean;
                            /** Format: uuid */
                            correlationId: string;
                            fields?: {
                                path?: string;
                                code?: string;
                            }[];
                        };
                    };
                };
            };
            /** @description Sem permissão para a operação. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            /** @example LOCATION_NOT_FOUND */
                            code: string;
                            message: string;
                            retryable: boolean;
                            /** Format: uuid */
                            correlationId: string;
                            fields?: {
                                path?: string;
                                code?: string;
                            }[];
                        };
                    };
                };
            };
        };
    };
}
